#!/usr/bin/env bash
# Provision a local dev Synapse + one test account. Idempotent-ish: re-running
# is safe except register step errors if the user already exists (ignore that).
# Run from this directory: `./provision.sh`
set -euo pipefail

SERVER_NAME=localhost
TEST_USER="${TEST_USER:-igni}"
TEST_PASS="${TEST_PASS:-dev-password}" # local-only; override via env
TEST_ACCOUNT_FILE=./test-account.env

# 1. Generate config + signing key on first run only.
if [ ! -f data/homeserver.yaml ]; then
	echo ">> generating Synapse config for server '$SERVER_NAME'"
	docker compose run --rm --no-deps synapse generate
else
	echo ">> data/homeserver.yaml exists, skipping generate"
fi

# 2. Start Synapse.
echo ">> starting Synapse"
docker compose up -d

# 3. Wait for the client-server API to answer.
echo ">> waiting for http://localhost:8008/_matrix/client/versions"
for i in $(seq 1 30); do
	if curl -fsS "http://localhost:8008/_matrix/client/versions" >/dev/null 2>&1; then
		echo ">> Synapse is up"
		break
	fi
	sleep 1
	[ "$i" -eq 30 ] && {
		echo "!! Synapse did not come up in 30s"
		exit 1
	}
done

# 4. Register the test account (non-interactive). Fails if it already exists.
echo ">> registering test account '$TEST_USER' (ok if it already exists)"
docker compose exec -T synapse \
	register_new_matrix_user \
	-u "$TEST_USER" -p "$TEST_PASS" -a -c /data/homeserver.yaml \
	"http://localhost:8008" || echo ">> '$TEST_USER' likely already exists, continuing"

# 5. Persist creds for later bursts (gitignored).
cat >"$TEST_ACCOUNT_FILE" <<EOF
# Generated by provision.sh — local dev only, gitignored.
SYNAPSE_HOMESERVER_URL=http://localhost:8008
SYNAPSE_TEST_USER=$TEST_USER
SYNAPSE_TEST_PASSWORD=$TEST_PASS
SYNAPSE_TEST_MXID=@$TEST_USER:$SERVER_NAME
EOF
echo ">> done. Creds in $TEST_ACCOUNT_FILE (gitignored). MXID: @$TEST_USER:$SERVER_NAME"
